name: stolby_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Annotations
  freezed_annotation: ^2.2.0

  # Routing
  auto_route: ^5.0.4
  url_launcher: ^6.1.12

  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.3.0

  # Bloc
  flutter_bloc: ^8.1.3

  # Core packages
  dartz: ^0.10.1
  uuid: ^3.0.7
  rxdart: ^0.27.7
  kt_dart: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  image: ^3.0.0

  # Local storage
  shared_preferences: ^2.2.0

  # DB
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.16

  # Permissions
  permission_handler: ^10.4.3

  # Map & Geolocation
  mapbox_gl: ^0.16.0
  location: ^4.3.0
  latlong2: ^0.9.0
  maps_launcher: ^2.2.0

  # UI Widgets
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.2
  animations: ^2.0.7
  flutter_staggered_animations: ^1.1.1

  # Social media sharing
  share_plus: ^7.1.0

  # Icons
  cupertino_icons: ^1.0.5
  community_material_icon: ^5.9.55

dev_dependencies:
  # Tests
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mockito: ^5.4.0

  # Code generation
  build_runner: ^2.4.6
  freezed: ^2.3.4
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.4.0
  drift_dev: ^2.8.2

  # Static analysis
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/maps.db
    - assets/rocks.db

