// Mocks generated by Mockito 5.0.16 from annotations
// in stolby_flutter/test/application/rock_list/rock_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stolby_flutter/domain/core/failures.dart' as _i5;
import 'package:stolby_flutter/domain/feature/rocks_list/entities/detailed_rock_entity.dart'
    as _i7;
import 'package:stolby_flutter/domain/feature/rocks_list/entities/rock_list_item_entity.dart'
    as _i6;
import 'package:stolby_flutter/domain/feature/rocks_list/i_rock_list_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IRockListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRockListRepository extends _i1.Mock
    implements _i3.IRockListRepository {
  MockIRockListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i6.RockListItemEntity>>>
      getRocksList() => (super.noSuchMethod(Invocation.method(#getRocksList, []),
          returnValue:
              Future<_i2.Either<_i5.DatabaseFailure, List<_i6.RockListItemEntity>>>.value(
                  _FakeEither_0<_i5.DatabaseFailure,
                      List<_i6.RockListItemEntity>>())) as _i4.Future<
          _i2.Either<_i5.DatabaseFailure, List<_i6.RockListItemEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i7.DetailedRockEntity>>
      getSingleRock(int? id) => (super.noSuchMethod(
          Invocation.method(#getSingleRock, [id]),
          returnValue: Future<
                  _i2.Either<_i5.DatabaseFailure, _i7.DetailedRockEntity>>.value(
              _FakeEither_0<_i5.DatabaseFailure, _i7.DetailedRockEntity>())) as _i4
          .Future<_i2.Either<_i5.DatabaseFailure, _i7.DetailedRockEntity>>);
  @override
  String toString() => super.toString();
}
